global:
  exp_name: flare22-stcn
  exist_ok: False
  debug: true
  cfg_transform: configs/cps/transform.yaml
  save_dir: runs
  device: cuda:0
  pretrained: null
  resume: null
  stage: refine
trainer:
  name: SemiSupervisedTrainer
  args:
    use_fp16: true
    num_iterations: 10000
    clip_grad:  10.0
    evaluate_interval: 1
    print_interval: 20
    save_interval: 1000
callbacks:
  - name: CPSCallbacks
    args: null
  - name: LoggerCallbacks
    args: null 
  - name: TwoStreamCheckpointCallbacks
    args:
      best_key: dice-avg
  - name: TwoStreamVisualizerCallbacks
    args: null
  #- name: WandbCallbacks
   # args: 
    #  username: kaylode
     # project_name: flare22
model:
  name: CrossPseudoSupervision
  args:
    model1:
      name: BaseSegModel
      args:
        model_name: unetplusplus
        encoder_name: efficientnet-b0
        in_channels: 1
        pretrained: False
    model2:
      name: BaseSegModel
      args:
        model_name: deeplabv3plus
        encoder_name: efficientnet-b0
        in_channels: 1
        pretrained: False
loss:
  name: CPSLoss
  args:
    sup_criterion:
      name: MultiLoss
      args:
        weights: null
        losses:
          - name: CELoss
            args: {}
          - name: DiceLoss
            args: {}
    unsup_criterion:
      name: DiceLoss
      args: {}
    consistency: 0.1
    consistency_rampup: 200.0
metrics:
- name: mIOU
  args:
- name: DiceScore
  args:
    calc_each_class: True
optimizer:
  name: AdamW
  args:
    lr: 0.0001
    weight_decay: 0.0000001
    betas:
    - 0.937
    - 0.999
scheduler:
  name: SchedulerWrapper
  args:
    scheduler_name: cosine2
    t_initial: 20
    t_mul: 0.95
    eta_mul: 0.95
    eta_min: 1.0e-07
data:
  dataset:
    train:
      name: FLARE22NormalDataset
      args:
        root_dir: /content/data/flare2022/labelled-processed320clip/
        csv_path: /content/data/flare2022/labelled-processed320clip/train.csv
        sample_fp: 5 #steps between samples
        max_frames: 30
    unsup_train:
      name: VolumeFolderDataset
      args:  
        root_dir: /content/data/flare2022/labelled-processed320clip/TrainImage/
        sample_fp: 5 #steps between samples
        max_frames: 5
    val:
      name: FLARE22NormalValDataset
      args:
        root_dir: /content/data/flare2022/labelled-processed320clip/
        csv_path: /content/data/flare2022/labelled-processed320clip/val.csv
        sample_fp: 2 #steps between samples
        max_frames: -1 #maximum 
  dataloader:
    train:
      name: TwoStreamDataLoader
      args:
        batch_sizes: [1,1]
        drop_last: false
        shuffle: false
    val:
      name: DataLoaderWithCollator
      args:
        batch_size: 1
        drop_last: false
        shuffle: false