global:
  exp_name: null
  exist_ok: False
  debug: True
  cfg_transform: configs/semantic2D/flare22/transform.yaml
  save_dir: ./runs
  device: cuda:0
  weights: null
  save_visualization: True
model:
  name: BaseSegModel
  args:
    model_name: unetplusplus
    encoder_name: efficientnet-b2
    in_channels: 1
    pretrained: false
data: 
  dataset:
    name: VolumeFolderDataset
    args:
      root_dir: ../data/numpy/flare2022-validation/Validation
      max_frames: -1
      sample_fp: 1
  dataloader:
    name: DataLoaderWithCollator
    args:
      batch_size: 1
      drop_last: False
      shuffle: False