global:
  exp_name: flare22-normal
  exist_ok: False
  debug: true
  cfg_transform: configs/flare22v2/normal/transform.yaml
  save_dir: runs
  device: cuda:0
  weights: null
  stage: reference
  save_visualization: True
model:
  name: TransUnetPE
  args:
    model_name: R50-ViT-B_16
    img_size: 512 
    in_channels: 3
    pretrained: False
    use_positional_encoding: True
data: 
  dataset:
    name: FLARE22V2TestDataset
    args:
      root_dir: data/flare22/npy/validation/ValidationImage
      sample_fp: 1
      max_ref_frames: -1
  dataloader:
    name: DataLoaderWithCollator
    args:
      batch_size: 1
      drop_last: False
      shuffle: False