global:
  exp_name: stcn_r50-flare22slices
  exist_ok: true
  debug: true
  cfg_transform: configs/semantic2D/flare22v2/stcn/transform.yaml
  save_dir: /content/main/runs
  device: cuda:0
  pretrained: null
  resume: null
  stage: refine
trainer:
  name: SupervisedTrainer
  args:
    use_fp16: true
    num_iterations: 60000
    clip_grad: 10.0
    evaluate_interval: 1
    print_interval: 100
    save_interval: 500
callbacks:
- name: LoggerCallbacks
  args: null
- name: STCNCallbacks
  args:
    skip_values:
    - 3
    - 4
    - 5
    - 7
    - 3
    increase_skip_fraction:
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.9
    - 1.0
- name: CheckpointCallbacks
  args:
    best_key: dice-avg
- name: VolumeVisualizerCallbacks
  args: null
- name: WandbCallbacks
  args:
    username: kaylode
    project_name: flare22
model:
  name: STCNModel
  args:
    single_object: false
    key_backbone: swin
    value_backbone: swin
    pretrained_backbone: true
    top_k_eval: 20
    max_k: 200
    mem_every_eval: 5
    include_last_val: true
    pretrained: true
    bidirectional: True
loss:
  name: STCNLossV2
  args:
    weights: null
    losses:
    - name: OhemCELoss
      args: 
        thresh: 0.5
    - name: LovaszSoftmax
      args: {}
metrics:
- name: mIOU
  args: null
- name: DiceScore
  args:
    calc_each_class: true
optimizer:
  name: AdamW
  args:
    lr: 0.0001
    weight_decay: 1.0e-07
    betas:
    - 0.937
    - 0.999
scheduler:
  name: SchedulerWrapper
  args:
    scheduler_name: multistep
    milestones:
    - 45000
    - 55000
    gamma: 0.5
data:
  dataset:
    train:
      name: ConcatDataset
      args:
        datasets:
          - name: FLARE22V2STCNTrainDataset
            args:
              root_dir: ../data/slices/processed/train/
              csv_path: ../data/slices/processed/train/train.csv
              use_aug: True
          - name: FLARE22V2STCNTrainDataset
            args:
              root_dir: ../data/slices/processed/unlabeled/
              csv_path: ../data/slices/processed/unlabeled/pseudo_unlabelled.csv
              use_aug: True
          - name: FLARE22V2STCNTrainDataset
            args:
              root_dir: ../data/slices/processed/unlabeled/
              csv_path: ../data/slices/processed/unlabeled/pseudo_unlabelled2.csv
              use_aug: True
    val:
      name: FLARE22V2STCNValDataset
      args:
        root_dir: ../data/npy_normalized/train/
        csv_path: ../data/npy_normalized/train/val.csv
  dataloader:
    train:
      name: DataLoaderWithCollator
      args:
        batch_size: 2
        drop_last: true
        shuffle: true
    val:
      name: DataLoader
      args:
        batch_size: 1
        drop_last: false
        shuffle: false