# Copyright The hcmus team.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is Conda environment file
# Usage: `conda env update -f environment.yml`

name: flare

channels:
  - pytorch
  - huggingface
  - conda-forge

dependencies:
  - cudatoolkit=10.2
  - pytorch=1.10
  - torchvision

  # Examples
  - pip
  # CI/CD
  - pytest
  - pytest-order
  # pip install 
  - pip:
    - git+https://github.com/kaylode/theseus.git@v1.0.1
    - gitpython==3.1.27
    - progressbar2==4.0.0
    - monai==1.0.0
    - SimpleITK==2.0.2
    - imageio==2.21.2
    - nibabel==4.0.2
    - moviepy==1.0.3
    - einops==0.2.0
    - ml_collections==0.1.1