global:
  debug: true
  cfg_transform: configs/semantic/transform.yaml
  save_dir: runs
  device: cuda:0
  use_fp16: true
  pretrained: null
  resume: null
trainer:
  name: SupervisedTrainer
  args:
    num_iterations: 10000
    clip_grad:  10.0
    evaluate_interval:  1
    print_interval: 20
    save_interval: 1000
callbacks:
  - name: LoggerCallbacks
    args: null 
  - name: STCNCallbacks
    args: null
  - name: TensorboardCallbacks
    args: null
model:
  name: STCNModel
  args:
    num_classes: 4
    local_rank: 0
    single_object: false
loss:
  name: STCNLoss
  args: null
metrics:
- name: mIOU
  args:
    ignore_index: 0
optimizer:
  name: AdamW
  args:
    lr: 0.001
    weight_decay: 0.0005
    betas:
    - 0.937
    - 0.999
scheduler:
  name: SchedulerWrapper
  args:
    scheduler_name: cosine2
    t_initial: 7
    t_mul: 0.9
    eta_mul: 0.9
    eta_min: 1.0e-06
data:
  dataset:
    train:
      name: Brats21Dataset
      args:
        volume_dir: /content/brats21-processed/imagesTr",
        label_dir: /content/brats21-processed/labelsTr",
        target_shape: 240
        max_jump: 5 #initial
    val:
      name: Brats21Dataset
      args:
        volume_dir: /content/brats21-processed/imagesTr",
        label_dir: /content/brats21-processed/labelsTr",
        target_shape: 240
        max_jump: 5 #initial
  dataloader:
    train:
      name: DistributedDataloader
      args:
        batch_size: 32
        drop_last: false
        shuffle: true
    val:
      name: DistributedDataloader
      args:
        batch_size: 32
        drop_last: false
        shuffle: true
