global:
  debug: True
  cfg_transform: configs/sample/transform.yaml
  save_dir: runs
  device: cuda:0
  weights: null
model:
  name: BaseSegModel
  args:
    name: unetplusplus
    encoder_name: efficientnet-b0

data: 
  dataset:
    name: TestCSVDataset
    args:
      image_dir: data/images
      txt_classnames: configs/sample/classes.txt

  dataloader:
    name: DataLoaderWithCollator
    args:
      batch_size: 64
      drop_last: True
      shuffle: True
