from .normal_visualize_callbacks import NormalVisualizerCallbacks
from .stcn_callback import STCNCallbacks
from theseus.semantic.callbacks import CALLBACKS_REGISTRY

CALLBACKS_REGISTRY.register(STCNCallbacks)
CALLBACKS_REGISTRY.register(NormalVisualizerCallbacks)
