global:
  exp_name: stcn-theseus
  exist_ok: False
  debug: true
  cfg_transform: configs/semantic2D/stcn/transform.yaml
  save_dir: runs
  device: cuda:0
  pretrained: null
  resume: null
  stage: refine
trainer:
  name: SupervisedTrainer
  args:
    use_fp16: true
    num_iterations: 10000
    clip_grad:  10.0
    evaluate_interval: 1
    print_interval: 20
    save_interval: 1000
callbacks:
  - name: LoggerCallbacks
    args: null 
  - name: STCNCallbacks
    args: null 
  - name: CheckpointCallbacks
    args:
      best_key: dice-avg
  - name: VolumeVisualizerCallbacks
    args: null
  - name: WandbCallbacks
    args: 
      username: kaylode
      project_name: flare22
model:
  name: STCNModel
  args:
    single_object: False
    top_k_eval: 20
    mem_every_eval: 5
    pretrained: True
loss:
  name: STCNLoss
  args: null
metrics:
- name: mIOU
  args:
- name: DiceScore
  args:
    calc_each_class: True
# - name: NormalizedSurfaceDistance
#   args:
#     calc_each_class: True
optimizer:
  name: AdamW
  args:
    lr: 0.0003
    weight_decay: 0.0000001
    betas:
    - 0.937
    - 0.999
scheduler:
  name: SchedulerWrapper
  args:
    scheduler_name: cosine2
    t_initial: 20
    t_mul: 0.95
    eta_mul: 0.95
    eta_min: 1.0e-07
data:
  dataset:
    train:
      name: AbdomenCT1KTrainDataset
      args:
        root_dir: /content/data/abdomenct1k/Subtask1-processed/
        csv_path: /content/data/abdomenct1k/Subtask1-processed/annotations/train.csv
        max_jump: 10 #initial
    val:
      name: AbdomenCT1KValDataset
      args:
        root_dir: /content/data/abdomenct1k/Subtask1-processed/
        csv_path: /content/data/abdomenct1k/Subtask1-processed/annotations/val.csv
  dataloader:
    train:
      name: DataLoader
      args:
        batch_size: 16
        drop_last: false
        shuffle: false
        sampler:
          name: ReSampler
          args:
            num_repeat: 10
    val:
      name: DataLoader
      args:
        batch_size: 1
        drop_last: false
        shuffle: false