global:
  exp_name: null
  exist_ok: False
  debug: True
  cfg_transform: /content/main/configs/semantic2D/stcn/transform.yaml
  save_dir: runs
  device: cuda:0
  ref_weights: null
  prop_weights: null
  top_k: 20 # top k frames in memory to calculate affinity 
  mem_every: 5 # save frames every k step
  save_visualization: True
  strategy: all # strategy for choosing reference images
ref_model:
  name: BaseSegModel
  args:
    model_name: unetplusplus
    encoder_name : efficientnet-b0
    in_channels: 1

data: 
  dataset:
    name: AbdomenCT1KTestDataset
    args:
      root_dir: /content/data/abdomenct1k/Subtask1-processed/ValImage
      max_ref_frames: 64
  dataloader:
    name: DataLoaderWithCollator
    args:
      batch_size: 1
      drop_last: False
      shuffle: True