global:
  debug: True
  cfg_transform: configs/semantic/transform.yaml
  save_dir: runs
  device: cuda:0
  ref_weights: null
  prop_weights: null
  top_k: 20
  mem_every: 5
ref_model:
  name: BaseSegModel
  args:
    model_name: unetplusplus
    encoder_name : efficientnet-b0
    in_channels: 1

data: 
  dataset:
    name: Brats21Testset
    args:
      volume_dir: /content/brats21-processed/imagesTr
      label_dir: /content/brats21-processed/labelsTr
      target_shape: 240
  dataloader:
    name: DataLoader
    args:
      batch_size: 1
      drop_last: False
      shuffle: True