global:
  exp_name: flare22-normal
  exist_ok: False
  debug: true
  cfg_transform: configs/semantic2D/flare22v2/normal/transform.yaml
  save_dir: runs
  device: cuda:0
  weights: null
  stage: reference
  save_csv: True
  save_visualization: True
  use_uncertainty: False
  class_weights: configs/weights.txt
model:
  name: TransUnetPE
  args:
    model_name: R50-ViT-B_16
    img_size: 512 
    in_channels: 3
    pretrained: False
data: 
  dataset:
    name: FLARE22V2TestDataset
    args:
      root_dir: ../data/npy_normalized/validation/ValidationProcessedNpy
      sample_fp: 1
      max_ref_frames: -1
  dataloader:
    name: DataLoaderWithCollator
    args:
      batch_size: 1
      drop_last: False
      shuffle: False