global:
  exp_name: flare22-stcn
  exist_ok: False
  debug: true
  cfg_transform: configs/cps/transform_slices.yaml
  save_dir: runs
  device: cuda:0
  weights: null
  stage: reference
  save_csv: True
  save_visualization: True
  use_uncertainty: False
  class_weights: configs/weights.txt
model:
  name: BaseSegModel
  args:
    model_name: unetplusplus
    encoder_name: se_resnet50
    in_channels: 1
    pretrained: false

data: 
  dataset:
    name: FLARE22SlicesFolderDataset
    args:
      root_dir: ../data/slices/unlabelled/unlabelled_part3
  dataloader:
    name: DataLoaderWithCollator
    args:
      batch_size: 16
      drop_last: False
      shuffle: False