train:
  name: AlbCompose
  args:
    transforms:
      - name: AlbResize
        args:
          width: 512
          height: 512
      - name: AlbHorizontalFlip
        args:
      - name: AlbVerticalFlip
        args:
      - name: AlbGaussianBlur
        args:
      - name: AlbToTensorV2
val:
  name: AlbCompose
  args:
    transforms:
      - name: AlbResize
        args:
          width: 512
          height: 512
      - name: AlbToTensorV2

test:
  name: AlbCompose
  args:
    transforms:
      - name: AlbResize
        args:
          width: 512
          height: 512
      - name: AlbToTensorV2