global:
  debug: True
  cfg_transform: configs/sample/transform.yaml
  save_dir: runs
  device: cuda:0
  weights: null
  
model:
  name: BaseTimmModel
  args:
    name: convnext_small
    from_pretrained: False
    num_classes: 41

data: 
  dataset:
    name: ImageDataset
    args:
      image_dir: data/images
      txt_classnames: configs/sample/classes.txt

  dataloader:
    name: DataLoader
    args:
      batch_size: 64
      drop_last: True
      shuffle: True
