global:
  exp_name: flare22-stcn
  exist_ok: False
  debug: true
  cfg_transform: configs/semantic2D/flare22v2/cps/transform.yaml
  save_dir: runs
  device: cuda:0
  weights: null
  stage: reference
  save_csv: True
  save_visualization: True
  use_uncertainty: False
  class_weights: configs/weights.txt
model:
  name: CrossPseudoSupervision
  args:
    model1:
      name: TransUnetPE
      args:
        model_name: R50-ViT-B_16
        img_size: 512 
        in_channels: 3
        pretrained: False
    model2:
      name: BaseSegModel
      args:
        model_name: deeplabv3plus
        encoder_name: efficientnet-b3
        in_channels: 3
        pretrained: false
      
data: 
  dataset:
    name: FLARE22V2TestDataset
    args:
      root_dir: ../data/slices/unlabelled/unlabelled_part3
      sample_fp: 1
      max_ref_frames: -1
  dataloader:
    name: DataLoaderWithCollator
    args:
      batch_size: 1
      drop_last: False
      shuffle: False