global:
  exp_name: flare22-stcn
  exist_ok: False
  debug: true
  cfg_transform: configs/semantic2D/flare22/stcn/transform_slices.yaml
  save_dir: runs
  device: cuda:0
  pretrained: null
  resume: null
  stage: refine
trainer:
  name: SupervisedTrainer
  args:
    use_fp16: true
    num_iterations: 10000
    clip_grad:  10.0
    evaluate_interval: 1
    print_interval: 20
    save_interval: 1000
callbacks:
  - name: LoggerCallbacks
    args: null 
  - name: STCNCallbacks
    args: 
      skip_values: [2, 3, 5, 7, 5]  
      increase_skip_fraction: [0.1, 0.2, 0.3, 0.4, 0.9, 1.0] 
  - name: CheckpointCallbacks
    args:
      best_key: dice-avg
  - name: VolumeVisualizerCallbacks
    args: null
  - name: WandbCallbacks
    args: 
      username: kaylode
      project_name: flare22
model:
  name: STCNModel
  args:
    single_object: False
    key_backbone: resnet50-mod
    value_backbone: resnet18-mod
    pretrained_backbone: True
    top_k_eval: 20
    mem_every_eval: 5
    include_last_val: True # whether to use last frame to retrieve current
    pretrained: True
loss:
  name: STCNLossV2
  args:
    weights: null
    losses:
      - name: CELoss
        args: {}
      - name: DiceLoss
        args: {}
metrics:
- name: mIOU
  args:
- name: DiceScore
  args:
    calc_each_class: True
optimizer:
  name: AdamW
  args:
    lr: 0.0001
    weight_decay: 0.0000001
    betas:
    - 0.937
    - 0.999
scheduler:
  name: SchedulerWrapper
  args:
    scheduler_name: multistep
    milestones: [500, 1000, 1500]
    gamma: 0.1
data:
  dataset:
    train:
      name: FLARE22SlicesDataset
      args:
        root_dir: /content/data/flare2022-slices/
        csv_path: /content/data/flare2022-slices/train.csv
        max_jump: 3 #initial
    val:
      name: FLARE22ValDataset
      args:
        root_dir: /content/data/flare2022/labelled-processed320clip/
        csv_path: /content/data/flare2022/labelled-processed320clip/val.csv
  dataloader:
    train:
      name: DataLoaderWithCollator
      args:
        batch_size: 8
        drop_last: true
        shuffle: true
    val:
      name: DataLoader
      args:
        batch_size: 1
        drop_last: false
        shuffle: false