global:
  exp_name: null
  exist_ok: False
  debug: True
  cfg_transform: ../main/configs/semantic2D/flare22/transform.yaml
  save_dir: runs
  device: cuda:0
  ref_weights: null
  prop_weights: null
  save_visualization: True
  ref_strategy: largest-area # strategy for choosing reference images
  prop_strategy: all # strategy for propagating images

prop_model:
  key_backbone: resnet50-mod
  value_backbone: resnet18-mod
  top_k: 20 # top k frames in memory to calculate affinity 
  mem_every: 5 # save frames every k step
  include_last: True # whether to use last frame to retrieve current

ref_model:
  name: CrossPseudoSupervision
  args:
    model1:
      name: BaseSegModel
      args:
        model_name: unetplusplus
        encoder_name: efficientnet-b2
        in_channels: 1
        pretrained: True
    model2:
      name: BaseSegModel
      args:
        model_name: deeplabv3plus
        encoder_name: efficientnet-b2
        in_channels: 1
        pretrained: True

data: 
  dataset:
    name: FLARE22TestDataset
    args:
      root_dir: ../data/flare2022-processed/TestImage
      max_ref_frames: 64
      sample_fp: 5
  dataloader:
    name: DataLoaderWithCollator
    args:
      batch_size: 1
      drop_last: False
      shuffle: False