train:
  name: MonaiCompose
  args:
    transforms:
      - name: MonaiLoadImaged
        args:
          keys: [image, label]
      - name: MonaiUnsqueezeOnAxisd
        args:
          keys: [label]
          axis: 0
      - name: ToTensord
        args:
          keys: [image, label]

val:
  name: MonaiCompose
  args:
    transforms:
      - name: MonaiLoadImaged
        args:
          keys: [image, label]
      - name: MonaiUnsqueezeOnAxisd
        args:
          keys: [label]
          axis: 0
      - name: ToTensord
        args:
          keys: [image, label]